[package]
name = "libnet-rs"
version = "0.1.1"
authors = ["Rémi Oudin <oudin@crans.org>"]
build = "build.rs"
license-file = "LICENSE"
description = "A quick binding of libnet for Rust"

[dependencies]
libc = "0.2.43"

[build-dependencies]
pkg-config = "0.3.14"
